export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_LOGOUT_REQUEST = "ADMIN_LOGOUT_REQUEST";
export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS";
export const ADMIN_LOGOUT_FAIL = "ADMIN_LOGOUT_FAIL";

export const ADMIN_CUMMULATIVE_STATS_REQUEST =
  "ADMIN_CUMMULATIVE_STATS_REQUEST";
export const ADMIN_CUMMULATIVE_STATS_SUCCESS =
  "ADMIN_CUMMULATIVE_STATS_SUCCESS";
export const ADMIN_CUMMULATIVE_STATS_FAIL = "ADMIN_CUMMULATIVE_STATS_FAIL";

export const ADMIN_MANAGE_CATEGORIES_REQUEST =
  "ADMIN_MANAGE_CATEGORIES_REQUEST";
export const ADMIN_MANAGE_CATEGORIES_SUCCESS =
  "ADMIN_MANAGE_CATEGORIES_SUCCESS";
export const ADMIN_MANAGE_CATEGORIES_FAIL = "ADMIN_MANAGE_CATEGORIES_FAIL";

export const ADMIN_MANAGE_PRODUCT_REQUEST = "ADMIN_MANAGE_PRODUCT_REQUEST";
export const ADMIN_MANAGE_PRODUCT_SUCCESS = "ADMIN_MANAGE_PRODUCT_SUCCESS";
export const ADMIN_MANAGE_PRODUCT_FAIL = "ADMIN_MANAGE_PRODUCT_FAIL";

export const ADMIN_MANAGE_SELLER_LIST_REQUEST =
  "ADMIN_MANAGE_SELLER_LIST_REQUEST";
export const ADMIN_MANAGE_SELLER_LIST_SUCCESS =
  "ADMIN_MANAGE_SELLER_LIST_SUCCESS";
export const ADMIN_MANAGE_SELLER_LIST_FAIL = "ADMIN_MANAGE_SELLER_LIST_FAIL";

export const ADMIN_MANAGE_USERS_LIST_REQUEST =
  "ADMIN_MANAGE_USERS_LIST_REQUEST";
export const ADMIN_MANAGE_USERS_LIST_SUCCESS =
  "ADMIN_MANAGE_USERS_LIST_SUCCESS";
export const ADMIN_MANAGE_USERS_LIST_FAIL = "ADMIN_MANAGE_USERS_LIST_FAIL";

export const ADMIN_MANAGE_ADMIN_LIST_REQUEST =
  "ADMIN_MANAGE_ADMIN_LIST_REQUEST";
export const ADMIN_MANAGE_ADMIN_LIST_SUCCESS =
  "ADMIN_MANAGE_ADMIN_LIST_SUCCESS";
export const ADMIN_MANAGE_ADMIN_LIST_FAIL = "ADMIN_MANAGE_ADMIN_LIST_FAIL";

export const ADMIN_MANAGE_BUSINESS_CATEGORY_LIST_REQUEST =
  "ADMIN_MANAGE_BUSINESS_CATEGORY_LIST_REQUEST";
export const ADMIN_MANAGE_BUSINESS_CATEGORY_LIST_SUCCESS =
  "ADMIN_MANAGE_BUSINESS_CATEGORY_LIST_SUCCESS";
export const ADMIN_MANAGE_BUSINESS_CATEGORY_LIST_FAIL =
  "ADMIN_MANAGE_BUSINESS_CATEGORY_LIST_FAIL";
