export const FETCH_CATEGORY_DETAILS_REQUEST = "FETCH_CATEGORY_DETAILS_REQUEST";
export const FETCH_CATEGORY_DETAILS_SUCCESS = "FETCH_CATEGORY_DETAILS_SUCCESS";
export const FETCH_CATEGORY_DETAILS_FAIL = "FETCH_CATEGORY_DETAILS_FAIL";
