export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

export const FETCH_CATEGORY_DETAILS_REQUEST = "FETCH_CATEGORY_DETAILS_REQUEST";
export const FETCH_CATEGORY_DETAILS_SUCCESS = "FETCH_CATEGORY_DETAILS_SUCCESS";
export const FETCH_CATEGORY_DETAILS_FAIL = "FETCH_CATEGORY_DETAILS_FAIL";
