export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAIL = "GET_USER_ORDERS_FAIL";

export const GET_USER_ORDER_REQUEST = "GET_USER_ORDER_REQUEST";
export const GET_USER_ORDER_SUCCESS = "GET_USER_ORDER_SUCCESS";
export const GET_USER_ORDER_FAIL = "GET_USER_ORDER_FAIL";

export const GET_SELLER_ORDERS_REQUEST = "GET_SELLER_ORDERS_REQUEST";
export const GET_SELLER_ORDERS_SUCCESS = "GET_SELLER_ORDERS_SUCCESS";
export const GET_SELLER_ORDERS_FAIL = "GET_SELLER_ORDERS_FAIL";

export const GET_SELLER_ORDER_REQUEST = "GET_SELLER_ORDER_REQUEST";
export const GET_SELLER_ORDER_SUCCESS = "GET_SELLER_ORDER_SUCCESS";
export const GET_SELLER_ORDER_FAIL = "GET_SELLER_ORDER_FAIL";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAIL = "UPDATE_ORDER_STATUS_FAIL";
