export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL";

export const SELLER_SIGNUP_REQUEST = "SELLER_SIGNUP_REQUEST";
export const SELLER_SIGNUP_SUCCESS = "SELLER_SIGNUP_SUCCESS";
export const SELLER_SIGNUP_FAIL = "SELLER_SIGNUP_FAIL";

export const SELLER_LOGIN_WITH_GOOGLE_REQUEST =
  "SELLER_LOGIN_WITH_GOOGLE_REQUEST";
export const SELLER_LOGIN_WITH_GOOGLE_SUCCESS =
  "SELLER_LOGIN_WITH_GOOGLE_SUCCESS";
export const SELLER_LOGIN_WITH_GOOGLE_FAIL = "SELLER_LOGIN_WITH_GOOGLE_FAIL";

export const SELLER_LOGOUT_REQUEST = "SELLER_LOGOUT_REQUEST";
export const SELLER_LOGOUT_SUCCESS = "SELLER_LOGOUT_SUCCESS";
export const SELLER_LOGOUT_FAIL = "SELLER_LOGOUT_FAIL";

export const GET_SELLER_REQUEST = "GET_SELLER_REQUEST";
export const GET_SELLER_SUCCESS = "GET_SELLER_SUCCESS";
export const GET_SELLER_FAIL = "GET_SELLER_FAIL";

export const BUSINESS_DETAILS_REQUEST = "BUSINESS_DETAILS_REQUEST";
export const BUSINESS_DETAILS_SUCCESS = "BUSINESS_DETAILS_SUCCESS";
export const BUSINESS_DETAILS_FAIL = "BUSINESS_DETAILS_FAIL";
