export const SELLER_LOGIN_REQUEST = "SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS = "SELLER_LOGIN_SUCCESS";
export const SELLER_LOGIN_FAIL = "SELLER_LOGIN_FAIL";

export const SELLER_SIGNUP_REQUEST = "SELLER_SIGNUP_REQUEST";
export const SELLER_SIGNUP_SUCCESS = "SELLER_SIGNUP_SUCCESS";
export const SELLER_SIGNUP_FAIL = "SELLER_SIGNUP_FAIL";

export const SELLER_LOGOUT_REQUEST = "SELLER_LOGOUT_REQUEST";
export const SELLER_LOGOUT_SUCCESS = "SELLER_LOGOUT_SUCCESS";
export const SELLER_LOGOUT_FAIL = "SELLER_LOGOUT_FAIL";

export const SELLER_PROFILE_DETAILS_REQUEST = "SELLER_PROFILE_DETAILS_REQUEST";
export const SELLER_PROFILE_DETAILS_SUCCESS = "SELLER_PROFILE_DETAILS_SUCCESS";
export const SELLER_PROFILE_DETAILS_FAIL = "SELLER_PROFILE_DETAILS_FAIL";

export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_SUCCESS = "CREATE_BUSINESS_SUCCESS";
export const CREATE_BUSINESS_FAIL = "CREATE_BUSINESS_FAIL";

export const BUSINESS_DETAILS_REQUEST = "BUSINESS_DETAILS_REQUEST";
export const BUSINESS_DETAILS_SUCCESS = "BUSINESS_DETAILS_SUCCESS";
export const BUSINESS_DETAILS_FAIL = "BUSINESS_DETAILS_FAIL";
