export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGIN_WITH_GOOGLE_REQUEST = "USER_LOGIN_WITH_GOOGLE_REQUEST";
export const USER_LOGIN_WITH_GOOGLE_SUCCESS = "USER_LOGIN_WITH_GOOGLE_SUCCESS";
export const USER_LOGIN_WITH_GOOGLE_FAIL = "USER_LOGIN_WITH_GOOGLE_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_PROFILE_DETAILS_REQUEST = "USER_PROFILE_DETAILS_REQUEST";
export const USER_PROFILE_DETAILS_SUCCESS = "USER_PROFILE_DETAILS_SUCCESS";
export const USER_PROFILE_DETAILS_FAIL = "USER_PROFILE_DETAILS_FAIL";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";
