const routes = {
  home: "/",
  about: "/about",
  login: "/login",
  signup: "/signup",
  contact: "/contact-us",
  privacyPolicy: "/privacy-policy",
  faq: "/FAQ",
  termsOfService: "/terms-of-service",
  cart: "/cart",
  business: "/business/:businessId",
  categories: "/business/:businessId/categories/:categoryId",
  getProduct: "/business/products/:productId",
  notFound: "*",
  dashboard: "/users/account",
  profile: "/users/profile",
  editProfile: "/users/profile/edit",
  getAddresses: "/users/addresses",
  getAddress: "/users/addresses/:addressId",
  addAddress: "/users/addresses/new",
  editAddress: "/users/addresses/:addressId/edit",
  getOrders: "/users/orders/",
  getOrder: "/users/orders/:orderId",
  wishList: "/users/wishlist",
  changePassword: "/users/change-password",
  forgotPassword: "/users/forgot-password",
};

export default routes;
